### ISSUE TITLE
Macro PEG is turing complete

### ISSUE THREAD

**Issue by kagamilove0707** [macro-peg/macro_peg#17]
This news will make you surprised. Meanwhile, you will be disappointed.

When I see Macro PEG for the first time, I thought it looks like first-order predicate logic so it is Turing complete probably. Then, I proved Macro PEG is Turing complete now.

[BCT (Bitwise Cyclic Tag)](https://esolangs.org/wiki/Bitwise_Cyclic_Tag) is one of the minimal Turing completed programming language.
Below grammar only accepts the sequence of `program`, `initial data` and `output` which is the result of running `program` with `initial data`.

```
START = PARSE0("") !.;

PARSE0(A) = &"0" RUN0("0", "", A)
          / &"10" RUN1("0", "1", "0", A)
          / &"11" RUN1("1", "1", "1", A)
          / &"1\n" RUN1("1", "1", "", A)
          ;

PARSE(H, C, A) = &(H C "0") RUN0(H, C "0", A)
               / &(H C "10") RUN1("0", H, C "10", A)
               / &(H C "11") RUN1("1", H, C "11", A)
               / &(H C "1\n") RUN1(H, H, "", A)
               / &(H C "\n") PARSE0(A)
               ;

RUN0(H, C, A) = &(CONSUME(H, C, A) "0") NEXT(H, C, A "0", "", "")
              / &(CONSUME(H, C, A) "1") NEXT(H, C, A "1", "", "")
              /   CONSUME(H, C, A) "\n"
              ;

RUN1(L, H, C, A) = &(CONSUME(H, C, A) "0") NEXT(H, C, A "0", "0", "")
                 / &(CONSUME(H, C, A) "1") NEXT(H, C, A "1", "1", L)
                 /   CONSUME(H, C, A) "\n"
                 ;

NEXT(H, C, A, I, T) = &(CONSUME(H, C, A) "0") NEXT(H, C, A "0", I "0", T)
                    / &(CONSUME(H, C, A) "1") NEXT(H, C, A "1", I "1", T)
                    / &(CONSUME(H, C, A) "\n" I T) PARSE(H, C, A "\n")
                    ;

CONSUME(H, C, A) = H C _(!"\n" .)* "\n" A;

_(X) = X;
```

For example, this grammar accepts such a input:

```
010
01
1
10
0
0

```

Annotated version (it is not accepted by this grammar):

```
010 <-- program
01  <-- initial data
1   <-- command '0'  => delete leftmost '0'
10  <-- command '10' => append '0'
0   <-- command '0'  => delete leftmost '1'
0   <-- command '10' => do nothing
    <-- command '0'  => delete leftmost '0'
```

That is this grammar emulates BCT. In other words, this grammar generates the parser to match `output` on reading `program` and `initial data`. Of course, this grammar generates the parser to match infinity length string if running `program` with `initial data` is not halting.

Probably, we can write the grammar of Turing machine:it accepts Turing machine definition, initial data and execution processes (output). On the contrary, we can write the grammar of Macro PEG in Macro PEG (it is very strange, however C compiler write in C itself usually).

However, Turing complete is too strong for the parser generator because it is **undecidable**. **undecidable** means the string set accepted by the grammar cannot decide statically. It causes problems on optimization and another.

I guess Macro PEG is not **undecidable** if the arity of rules restricts one, like first-order predicate logic. I will try to prove it.

**Comment by kmizu** [comment]
Macro PEG is considered to be decidable.  Then, close it.

**Comment by kagamilove0707** [comment]
Sorry...
